const express = require('express')
const { listarContas } = require('./controladores/contas')
const { criarConta } = require('./controladores/criarconta')
const { validarEmail, validarCPF, verificarPropriedade, localizarNumeroConta, localizarNumero_conta, localizarNumeroOrigem, localizarNumeroDestino } = require('./utilitarios')
const { excluirConta } = require('./controladores/deletarconta')
const { deposito } = require('./controladores/depositar')
const { atualizarDados } = require('./controladores/atualizarDados')
const { sacar } = require('./controladores/sacar')
const { autenticarSenhaBanco, autenticarSenhaUsuario, autenticarOrigem, autenticadorSaldoExtrato } = require('./intermediario')
const { transferencia } = require('./controladores/transferir')
const { consultarSaldo } = require('./controladores/consultarsaldo')
const { extratoBancario } = require('./controladores/extrato')
const rotas = express()

rotas.get('/contas', autenticarSenhaBanco, listarContas)
rotas.get('/contas/saldo', autenticadorSaldoExtrato, consultarSaldo)
rotas.get('/contas/extrato', autenticadorSaldoExtrato, extratoBancario)
rotas.put('/contas/:numeroConta/usuario', localizarNumeroConta, verificarPropriedade, validarCPF, validarEmail, atualizarDados)
rotas.delete('/contas/:numeroConta', localizarNumeroConta, excluirConta)
rotas.post('/contas', validarCPF, validarEmail, criarConta)
rotas.post('/transacoes/depositar', localizarNumero_conta, deposito)
rotas.post('/transacoes/sacar', autenticarSenhaUsuario, localizarNumero_conta, sacar)
rotas.post('/transacoes/transferir', localizarNumeroOrigem, localizarNumeroDestino, autenticarOrigem, transferencia)

module.exports = rotas
